### ISSUE TITLE
Loading new properties fails

### ISSUE THREAD

**Issue by justin-hecht** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#26] opened 2017-03-13 12:22 UTC
If you try to load a new property, the StaticSaverLoaders.SaverLoaderHelper throws a StringIndexOutOfBoundsException.

Recreate:
Load a property from Toolbar in PropertyEditor

Problem found in version 1.4.09

**Comment by NikolaiLMS** [comment] 2017-03-13 12:45
Duplicate of #23.

**Closed by NikolaiLMS** 2017-03-13 12:45 UTC
Labels: bug
